"""empty message

Revision ID: 789e127c8760
Revises: cda29e49ebc7
Create Date: 2024-01-22 10:16:56.491955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789e127c8760'
down_revision = 'cda29e49ebc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
